spring.application.name=project
# spring.config.import=optional:classpath:application-dev.properties
spring.config.import=optional:classpath:application-deploy.properties

#-------------IMG---------------#
#################################
file.upload-dir=uploads/images
spring.data.web.pageable.one-indexed-parameters=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.open-in-view=false
# spring.devtools.restart.exclude=**/security/CustomUserDetail.class
# spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# server.servlet.encoding.charset=UTF-8
# server.servlet.encoding.enabled=true
# server.servlet.encoding.force=true
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.hibernate.orm.jdbc.bind=TRACE


# FRONTEND_URL=http://localhost:5173

